---
- name: Postgre SQL Database installation and configuration
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Install required packages
    apt:
      name:
        - wget
        - python3-psycopg2
        - acl
      state: latest

  - name: Set up Postgres 14 repo
    shell: |
      echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    args:
      warn: no

  - name: Install postgresql
    apt:
      name: postgresql-14
      update_cache: yes

  - name: Setting the postgresql listening port to *
    ansible.builtin.lineinfile:
      path: /etc/postgresql/14/main/postgresql.conf
      line: listen_addresses = '*'
      create: yes

  - name: Opening remote access for Postgresql
    ansible.builtin.lineinfile:
      path: /etc/postgresql/14/main/pg_hba.conf
      line: host    all             all             0.0.0.0/0               md5
      create: yes

  - name: Opening remote access for Postgresql 2
    ansible.builtin.lineinfile:
      path: /etc/postgresql/14/main/pg_hba.conf
      line: host    all             all             ::/0                    md5
      create: yes
